server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:testdb
#    username: root
#    password: pass1
  jpa:
    hibernate:
      show-sql: true
      driver:
        class:
          name: org.h2.Driver
      sql:
        dialect: org.hibernate.dialect.H2Dialect