spring:
# Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5234/test
    username: postgres
    password: root
# JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
    generate-ddl: true
# mail properties
  mail:
      host: smtp.gmail.com
      port: 587
      username: alalexalexal@gmail.com
      password: alexAl2110
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
            connectiontimeout: 5000
            timeout: 3000
            writetimeout: 5000

telegram:
  invitation:
      subject: Synergy invited you to join the Telegram Bot
      text: Please click on the link below to accept invitation and start Telegram Bot.
      url: https://msngr.link/tg/
  username: SynTestTelegram_bot
  token: 1697376349:AAHT3OkNetvyMOA20gykX8WL6Y313_qNp1I
  notifytext: Your Goal - "%s" is FAILED!
  api:
      url: https://api.telegram.org/bot
#      requestTemplate: /sendContact?chat_id={}&phone_number={}&first_name={}
  user:
    forContact: 956964015
#scheduling properties
dbscheduler:
      pickAndSortFinishedGoals:
        delay: 0 */7 * ? * *
      updateUserWithNullTelegramId:
        delay: 0 */9 * ? * *
scheduling:
        enabled: true

server:
  port: 8081



